# Generated by Django 4.2.4 on 2023-09-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('short_txt', models.TextField()),
                ('body', models.TextField()),
                ('date', models.CharField(max_length=12)),
                ('writer', models.TextField()),
            ],
        ),
    ]
