# Generated by Django 4.2.4 on 2023-09-27 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.TextField(default='-'),
        ),
    ]
