# Generated by Django 4.2.4 on 2023-09-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='catagory',
            field=models.TextField(default='-'),
        ),
    ]
