# Generated by Django 4.2.4 on 2023-08-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_main_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='fc',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='ins',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='tw',
            field=models.TextField(default='-'),
        ),
    ]
