# Generated by Django 4.2.4 on 2023-08-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_main_link_main_tell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='fc',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='ins',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='link',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='tell',
            field=models.CharField(default='-', max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(default='-', max_length=40),
        ),
    ]
